version: '3.8'
services:
  student-service:
    build: ./backend/student-service
    ports:
      - "8081:8081"
  registration-service:
    build: ./backend/registration-service
    ports:
      - "8082:8082"
  frontend-react:
    build: ./frontend-react
    ports:
      - "3000:3000"
  frontend-angular:
    build: ./frontend-angular
    ports:
      - "4200:4200"
